<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "products".
 *
 * @property integer $id
 * @property string $title
 * @property integer $client_id
 * @property string $article
 * @property string $barcode
 * @property integer $balance
 * @property string $created_at
 * @property string $updated_at
 */
class Balance extends \yii\db\ActiveRecord
{
    private $oldBalance;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'balance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id'], 'required'],
            [['min_balance','product_id','balance'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID', 
            'product_id' => 'ID продукта', 
            'balance' => 'Остаток', 
            'min_balance' => 'Минимальный остаток для уведомления'
        ];
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getBalance()
    {
        return self::hasOne(Balance::className(), ['id' => 'product_id']);
    }
}