<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "products".
 *
 * @property integer $id
 * @property string $title
 * @property integer $client_id
 * @property string $article
 * @property string $barcode
 * @property integer $balance
 * @property string $created_at
 * @property string $updated_at
 */
class Product extends \yii\db\ActiveRecord
{
    private $oldBalance;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'client_id'], 'required'],
            [['client_id', 'balance'], 'integer'],
            [['created_at', 'nomenclature', 'code_client', 'barcode', 'article', 'balance'], 'safe'],
            [['title', 'article', 'barcode', 'nomenclature'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Наименование',
            'nomenclature' => 'Номенклатура',
            'client_id' => 'Клиент',
            'article' => 'Артикуль',
            'code_client' => 'Код клиента',
            'barcode' => 'Штрих-код',
            'balance' => 'Остатки на складе',
            'created_at' => 'Дата добавления',
            'updated_at' => 'Дата обновления',
        ];
    }

    public function afterFind()
    {
        $this->oldBalance = $this->balance;
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!empty($changedAttributes['balance'])) {
            if ($insert) {
                $this->oldBalance = 0;
            }
            $analytics = ProductAnalytics::getOrCreateByDate($this->id);

            if ($this->oldBalance < $this->balance) {
                $analytics->increase = $this->balance - $this->oldBalance;
            } else {
                $analytics->decrease = $this->oldBalance - $this->balance;
            }

            $analytics->save();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}